modLoader="javafml"
loaderVersion="[21,)"
license="MIT"
issueTrackerURL="https://github.com/DaFuqs/fractal/issues"
[[mods]]
modId="fractal"
version="${version}"
displayName="Fractal"
logoFile="assets/fractal/icon.png"
credits="unascribed: original mod author, Mayaqq: Arch port"
authors="Dafuqs"
description='''
Adds item subgroups.
'''
[[dependencies.fractal]]
   modId="neoforge"
   mandatory=true
   versionRange="[21,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.fractal]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.21,1.22)"
   ordering="NONE"
   side="BOTH"
[[mixins]]
   config = "fractal.mixins.json"
[[mixins]]
   config = "fractal-common.mixins.json"